# Generated by Django 5.2.15 on 2026-07-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'meal entries',
                'ordering': ['date', 'logged_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.PositiveIntegerField(default=2000)),
                ('protein_g', models.PositiveIntegerField(default=150)),
                ('carbs_g', models.PositiveIntegerField(default=200)),
                ('fat_g', models.PositiveIntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('goal_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_carbs_g', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_fat_g', models.PositiveIntegerField(blank=True, null=True)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('calorie_diff', models.IntegerField(default=0, help_text='Positive = over goal, negative = under goal.')),
                ('protein_diff_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs_diff_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat_diff_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_day_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_nutrition_day_log_per_user')],
            },
        ),
    ]
